### ISSUE TITLE
listWorkspaces and listTables only returns empty array.

### ISSUE THREAD

**Issue by yakuzadave** [googleapis/nodejs-area120-tables#94]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-area120-tables/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: v16.5.0
  - npm version: 7.19.1
  - `@google/area120-tables` version: 1.3.0

#### Steps to reproduce

  1. Authenticate successfully using with ADC or OAuth2Client
      - For OAuth2Client, I had scopes for the following: 
          - https://www.googleapis.com/auth/tables
          - https://www.googleapis.com/auth/spreadsheets
          - https://www.googleapis.com/auth/drive
  2. Init TablesServiceClient
  3. Make request using TablesServiceClient.listWorkspaces() // expected Workspaces =2
  4. Returned values Promise resolve is the following:
  
 
`  [ [], null, null ]`

**Note**: This appears to be the case with the sample code listed in the [example](https://cloud.google.com/nodejs/docs/reference/area120-tables/latest#using-the-client-library) for listTables()

**Comment by bcoe** [comment]
@yakuzadave is this issue continuing to happen for you, it sounds like a problem with the API itself potentially (if it hasn't been corrected I can reach out to the product team).

**Comment by yakuzadave** [comment]
@bcoe I'll go ahead and give it a shot again and let you know if I am still running into the same issue.  I had been using AppScript and a POST method in the meantime as workaround.

**Comment by sofisl** [comment]
Hi @yakuzadave,

I wasn't able to reproduce your error. However, I had a very hard time authenticating properly! I added a new sample with proper authentication, that got me a list of tables in my account. Hope this helps! Feel free to reopen if it doesn't.
